# Generated by Django 3.2 on 2021-04-23 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority', models.CharField(choices=[('ESTAGIARIO', 'Estagiário'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior')], default='PLENO', max_length=25)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADA', 'Encerrada')], default='CRIADA', max_length=20)),
                ('contract_type', models.CharField(choices=[('PJ', 'PJ'), ('CLT', 'CLT')], max_length=15)),
                ('start_pub', models.DateField()),
                ('end_pub', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.position')),
            ],
        ),
    ]
