# Generated by Django 3.2 on 2021-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.TextField(null=True),
        ),
    ]
