# Generated by Django 3.2 on 2021-04-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210416_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.TextField(),
        ),
    ]
