# Generated by Django 3.2 on 2021-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210416_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_e',
            field=models.TextField(blank=True, null=True),
        ),
    ]
